# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zen_notice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zen_notice.proto',
  package='zen_notice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10zen_notice.proto\x12\nzen_notice\"\xd3\x01\n\rNoticeLineReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\x12\x12\n\ntrigger_ts\x18\x04 \x01(\x05\x12\x11\n\tdirection\x18\x05 \x01(\x05\x12\x15\n\rline_start_ts\x18\x06 \x01(\x05\x12\x13\n\x0bline_end_ts\x18\x07 \x01(\x05\x12\x0c\n\x04high\x18\x08 \x01(\x01\x12\x0b\n\x03low\x18\t \x01(\x01\x12\x10\n\x08sec_type\x18\n \x01(\t\x12\x16\n\x0ekline_start_ts\x18\x0b \x01(\x05\"0\n\rNoticeLineRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"S\n\rNoticeDrawReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\x12\x16\n\x0ekline_start_ts\x18\x04 \x01(\x05\"0\n\rNoticeDrawRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xf4\x01\n\x0eNoticeTradeReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08sec_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06period\x18\x04 \x01(\t\x12\x12\n\ntrade_type\x18\x05 \x01(\x05\x12\x17\n\x0fopen_cover_type\x18\x06 \x01(\x05\x12\x11\n\tdirection\x18\x07 \x01(\x05\x12\x12\n\ntrigger_ts\x18\x08 \x01(\x05\x12\x16\n\x0ekline_start_ts\x18\t \x01(\x05\x12\r\n\x05price\x18\n \x01(\x01\x12\x17\n\x0fstop_loss_price\x18\x0b \x01(\x01\x12\x10\n\x08\x65xt_info\x18\x0c \x01(\t\"1\n\x0eNoticeTradeRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe6\x01\n\x0fZenNoticeHandle\x12\x44\n\nNoticeLine\x12\x19.zen_notice.NoticeLineReq\x1a\x19.zen_notice.NoticeLineRsp\"\x00\x12\x44\n\nNoticeDraw\x12\x19.zen_notice.NoticeDrawReq\x1a\x19.zen_notice.NoticeDrawRsp\"\x00\x12G\n\x0bNoticeTrade\x12\x1a.zen_notice.NoticeTradeReq\x1a\x1a.zen_notice.NoticeTradeRsp\"\x00\x62\x06proto3'
)




_NOTICELINEREQ = _descriptor.Descriptor(
  name='NoticeLineReq',
  full_name='zen_notice.NoticeLineReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zen_notice.NoticeLineReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='zen_notice.NoticeLineReq.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='zen_notice.NoticeLineReq.period', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_ts', full_name='zen_notice.NoticeLineReq.trigger_ts', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='zen_notice.NoticeLineReq.direction', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_start_ts', full_name='zen_notice.NoticeLineReq.line_start_ts', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_end_ts', full_name='zen_notice.NoticeLineReq.line_end_ts', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='zen_notice.NoticeLineReq.high', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='zen_notice.NoticeLineReq.low', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_type', full_name='zen_notice.NoticeLineReq.sec_type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kline_start_ts', full_name='zen_notice.NoticeLineReq.kline_start_ts', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=244,
)


_NOTICELINERSP = _descriptor.Descriptor(
  name='NoticeLineRsp',
  full_name='zen_notice.NoticeLineRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='zen_notice.NoticeLineRsp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='zen_notice.NoticeLineRsp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=294,
)


_NOTICEDRAWREQ = _descriptor.Descriptor(
  name='NoticeDrawReq',
  full_name='zen_notice.NoticeDrawReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zen_notice.NoticeDrawReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='zen_notice.NoticeDrawReq.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='zen_notice.NoticeDrawReq.period', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kline_start_ts', full_name='zen_notice.NoticeDrawReq.kline_start_ts', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=379,
)


_NOTICEDRAWRSP = _descriptor.Descriptor(
  name='NoticeDrawRsp',
  full_name='zen_notice.NoticeDrawRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='zen_notice.NoticeDrawRsp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='zen_notice.NoticeDrawRsp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=429,
)


_NOTICETRADEREQ = _descriptor.Descriptor(
  name='NoticeTradeReq',
  full_name='zen_notice.NoticeTradeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zen_notice.NoticeTradeReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_type', full_name='zen_notice.NoticeTradeReq.sec_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='zen_notice.NoticeTradeReq.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='zen_notice.NoticeTradeReq.period', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trade_type', full_name='zen_notice.NoticeTradeReq.trade_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open_cover_type', full_name='zen_notice.NoticeTradeReq.open_cover_type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='zen_notice.NoticeTradeReq.direction', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_ts', full_name='zen_notice.NoticeTradeReq.trigger_ts', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kline_start_ts', full_name='zen_notice.NoticeTradeReq.kline_start_ts', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='zen_notice.NoticeTradeReq.price', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_loss_price', full_name='zen_notice.NoticeTradeReq.stop_loss_price', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ext_info', full_name='zen_notice.NoticeTradeReq.ext_info', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=676,
)


_NOTICETRADERSP = _descriptor.Descriptor(
  name='NoticeTradeRsp',
  full_name='zen_notice.NoticeTradeRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='zen_notice.NoticeTradeRsp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='zen_notice.NoticeTradeRsp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=727,
)

DESCRIPTOR.message_types_by_name['NoticeLineReq'] = _NOTICELINEREQ
DESCRIPTOR.message_types_by_name['NoticeLineRsp'] = _NOTICELINERSP
DESCRIPTOR.message_types_by_name['NoticeDrawReq'] = _NOTICEDRAWREQ
DESCRIPTOR.message_types_by_name['NoticeDrawRsp'] = _NOTICEDRAWRSP
DESCRIPTOR.message_types_by_name['NoticeTradeReq'] = _NOTICETRADEREQ
DESCRIPTOR.message_types_by_name['NoticeTradeRsp'] = _NOTICETRADERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NoticeLineReq = _reflection.GeneratedProtocolMessageType('NoticeLineReq', (_message.Message,), {
  'DESCRIPTOR' : _NOTICELINEREQ,
  '__module__' : 'zen_notice_pb2'
  # @@protoc_insertion_point(class_scope:zen_notice.NoticeLineReq)
  })
_sym_db.RegisterMessage(NoticeLineReq)

NoticeLineRsp = _reflection.GeneratedProtocolMessageType('NoticeLineRsp', (_message.Message,), {
  'DESCRIPTOR' : _NOTICELINERSP,
  '__module__' : 'zen_notice_pb2'
  # @@protoc_insertion_point(class_scope:zen_notice.NoticeLineRsp)
  })
_sym_db.RegisterMessage(NoticeLineRsp)

NoticeDrawReq = _reflection.GeneratedProtocolMessageType('NoticeDrawReq', (_message.Message,), {
  'DESCRIPTOR' : _NOTICEDRAWREQ,
  '__module__' : 'zen_notice_pb2'
  # @@protoc_insertion_point(class_scope:zen_notice.NoticeDrawReq)
  })
_sym_db.RegisterMessage(NoticeDrawReq)

NoticeDrawRsp = _reflection.GeneratedProtocolMessageType('NoticeDrawRsp', (_message.Message,), {
  'DESCRIPTOR' : _NOTICEDRAWRSP,
  '__module__' : 'zen_notice_pb2'
  # @@protoc_insertion_point(class_scope:zen_notice.NoticeDrawRsp)
  })
_sym_db.RegisterMessage(NoticeDrawRsp)

NoticeTradeReq = _reflection.GeneratedProtocolMessageType('NoticeTradeReq', (_message.Message,), {
  'DESCRIPTOR' : _NOTICETRADEREQ,
  '__module__' : 'zen_notice_pb2'
  # @@protoc_insertion_point(class_scope:zen_notice.NoticeTradeReq)
  })
_sym_db.RegisterMessage(NoticeTradeReq)

NoticeTradeRsp = _reflection.GeneratedProtocolMessageType('NoticeTradeRsp', (_message.Message,), {
  'DESCRIPTOR' : _NOTICETRADERSP,
  '__module__' : 'zen_notice_pb2'
  # @@protoc_insertion_point(class_scope:zen_notice.NoticeTradeRsp)
  })
_sym_db.RegisterMessage(NoticeTradeRsp)



_ZENNOTICEHANDLE = _descriptor.ServiceDescriptor(
  name='ZenNoticeHandle',
  full_name='zen_notice.ZenNoticeHandle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=730,
  serialized_end=960,
  methods=[
  _descriptor.MethodDescriptor(
    name='NoticeLine',
    full_name='zen_notice.ZenNoticeHandle.NoticeLine',
    index=0,
    containing_service=None,
    input_type=_NOTICELINEREQ,
    output_type=_NOTICELINERSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NoticeDraw',
    full_name='zen_notice.ZenNoticeHandle.NoticeDraw',
    index=1,
    containing_service=None,
    input_type=_NOTICEDRAWREQ,
    output_type=_NOTICEDRAWRSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NoticeTrade',
    full_name='zen_notice.ZenNoticeHandle.NoticeTrade',
    index=2,
    containing_service=None,
    input_type=_NOTICETRADEREQ,
    output_type=_NOTICETRADERSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ZENNOTICEHANDLE)

DESCRIPTOR.services_by_name['ZenNoticeHandle'] = _ZENNOTICEHANDLE

# @@protoc_insertion_point(module_scope)
